# Generated by Django 4.1.2 on 2023-05-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='text',
        ),
    ]
