# Generated by Django 4.1.2 on 2023-05-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_conversation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
