# Generated by Django 4.1.2 on 2023-05-19 17:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
