# Generated by Django 4.1.2 on 2023-05-20 03:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion_room',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
