# Generated by Django 4.1.2 on 2023-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_discussion_room_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='group',
        ),
        migrations.AlterField(
            model_name='discussion_room',
            name='cover_img',
            field=models.ImageField(blank=True, default='../media/discussion_room/download.jpeg', null=True, upload_to='discussion_room/'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='chat.discussion_room'),
        ),
    ]
